### ISSUE TITLE
Build a Docker container

### ISSUE THREAD

**Issue by kgostic** [CDCgov/cfa-rt-postprocessing#5]

**Comment by amondal2** [comment]
I'm not sure exactly what the container needs to do, but dropping some code here for how I handled automated build + push to ACR (and re-deploy the container app) for any pushes to `main` https://github.com/CDCgov/cfa-config-validation/blob/master/.github/workflows/deploy.yaml

The only caveat with this approach is that the `latest` tag doesn't seem to work (ie, the container app didn't re-pull the container), so we explicitly use the git SHA.

**Comment by natemcintosh** [comment]
That will definitely be useful
