### ISSUE TITLE
Build merged_draws.parquet and merged_summaries.parquet

### ISSUE THREAD

**Issue by kgostic** [CDCgov/cfa-rt-postprocessing#7]

**Comment by kgostic** [comment]
@zsusswein will review

**Comment by natemcintosh** [comment]
So, going off the [output structure docs](https://github.com/CDCgov/cfa-epinow2-pipeline/blob/main/README.md#directories), the raw output will have form
```
az://rt-output/
├── job_<job_id>/
│   ├── raw_samples/
│   │   ├── samples_<task_id>.parquet
│   ├── summarized_quantiles/
│   │   ├── summarized_<task_id>.parquet
│   ├── diagnostics/
│   │   ├── diagnostics_<task_id>.parquet
│   ├── tasks/
│   │   ├── task_<task_id>/
│   │   │   ├── model.rds
│   │   │   ├── metadata.json
│   │   │   ├── stdout.log
│   │   │   └── stderr.log
│   ├── job_metadata.json
```

- If re-runs end up in the same job, that makes created `merged_...` files a little simpler, as they can go in the same job folder.
- If re-runs end up in a different job, then we would put the `merged...` files in the [production database](https://github.com/CDCgov/cfa-rt-postprocessing/issues/9)?

I guess I'm slightly unclear on the difference between these `merged_...` files and the "production database".

**Comment by natemcintosh** [comment]
Assuming the section in [this PR updating the README](https://github.com/CDCgov/cfa-rt-postprocessing/blob/ea011c30ed636f762f236f49b02766d65d755d63/README.md) on "outputs" is correct, I think I understand how this all fits together.

**Comment by natemcintosh** [comment]
Looking at the desired output structure again
```
<root-subdir>/               # E.g. "NSSP_Rt/EpiNow2" or "backfill-experiment"
├── <release-name>/          # E.g. "20241009"
│   ├── internal-review/
|   |   ├── job_<jobid>/     # Jobs are disease-specific in production
|   |   |   ├── merged.csv
|   |   |   ├── plots/
|   |   |   |   ├── choropleth.png
|   |   |   |   ├── lineinterval.png
|   |   |   |   ├── timeseries/
|   |   |   |   |   ├── <location>.png
|   |   |   |   |   ├── <location>.png
|   |   |   |   ├── ...
|   |   ├── job_<jobid>/
|   |   |   ├── merged.csv
|   |   |   ├── plots/
|   |   |   |   ├── choropleth.png
|   |   |   |   ├── lineinterval.png
|   |   |   |   ├── timeseries/
|   |   |   |   |   ├── <location>.png
|   |   |   |   |   ├── <location>.png
|   |   |   |   |   ├── ...
|   ├── release/
|   |   ├── merged_release.csv
|   |   ├── <rundate>_<disease1>_map_data.csv
|   |   ├── <rundate>_<disease2>_map_data.csv
|   |   ├── <rundate>_<disease1>_timeseries_data.csv
|   |   ├── <rundate>_<disease2>_timeseries_data.csv
```
the config generator puts all the diseases in one job. However, we might still have multiple jobs for other reasons, e.g. different models. (Note that the [config modifier](https://github.com/CDCgov/cfa-config-generator/blob/95bccc1d3b9351ce20a5a49c16483076f315b7d9/cli/console.py#L147) gives a new task name for modifications, but uses the same job name)

## Splitting merged files between the job id folders
Do we want to put the merged files in `internal-review/` as:
1. One big file at `internal-review/summaries.parquet` or `internal-review/samples.parquet`
1. Separate files under each job.

If we go for option 2, then we may have to add logic for picking which job folder to look in. If we stick everything in one, then we can keep all the filtering logic in one spot.

## Splitting plots between the job id folders
I think it still makes sense to split the plots into job folders, but am open to suggestions.
